# Site settings
name: Ifeoma Okereke
description: "Software Engineer | Public Speaker | Co-organizer, Write Speak Code NYC"
url: ""


# Delete the lines you don't need
# about 5 elements are recomended
github_username:  iruth
twitter_username: ifeomaro
linkedin_username: ifeomaokereke
medium_username:  ifeomaro
stack_of_username: 2688283/iruth
#blog_url: "/blog"


avatar: yes
#avatar_img_path: "imgs/avatar.jpg""
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar_img_path: "https://pbs.twimg.com/profile_images/1119042497672622080/MtUBlHl4_400x400.jpg"


front_img: yes
front_img_path: "imgs/bg.jpg"
#front_img_path: "https://external.url/image.jpg"


favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty
